%% find_trim_inflow function

function[trim_inflow, CH_TPP_UH60_FF, CY_TPP_UH60_FF, beta, beta_dot, beta_star, theta, theta_dot, theta_star]...
    = find_trim_inflow(mu, psi, CT_constant_T, sigma, f, A,L_tr, R, vb, CP_UH60_FF, theta_tw,lambda_TPP_UH60_FF, ...
    omega, x_cg, y_cg, h, T, lock, a, cd0)
%% constants
M_yF_UH60_FF = 0;
M_xF_UH60_FF = 0;
CH_TPP_UH60_FF = 0;
CY_TPP_UH60_FF = 0;
epsilon = 1;
theta_tw = 0;
%% defining functions
beta_1c = @(CH_TPP_UH60_FF) ((-x_cg./h)+(M_yF_UH60_FF./(T.*h))+...
    (CH_TPP_UH60_FF./CT_constant_T))./(1+(((vb.^2)-1)./(lock.*(2.*h.*CT_constant_T./R./sigma./a))));
beta_1s = @(CY_TPP_UH60_FF) ((y_cg/h)-(M_xF_UH60_FF/(T*h))+...
    (CY_TPP_UH60_FF./CT_constant_T ))./(1+(((vb.^2)-1)...
    ./(lock.*(2.*h.*CT_constant_T./R./sigma./a))));
alpha_shaft = @(CH_TPP_UH60_FF) ((((x_cg./h)-(M_yF_UH60_FF./(T.*h))+...
    (((((vb.^2)-1)./(lock.*(2.*h.*CT_constant_T./R./sigma./a)))).*...
    CH_TPP_UH60_FF./CT_constant_T )))./(1+(((vb.^2)-1)./...
    (lock.*(2.*h.*CT_constant_T./R./sigma./a)))))+...
    ((1/2).*(f./A).*(mu.^2)./CT_constant_T );
phi_shaft = @(CY_TPP_UH60_FF)((((y_cg./h)-(M_xF_UH60_FF./(T.*h))-...
    (((((vb.^2)-1)./(lock.*(2.*h.*CT_constant_T./R./sigma./a)))).*CY_TPP_UH60_FF./...
    CT_constant_T )))./...
    (1+(((vb^2)-1)./(lock.*(2.*h.*CT_constant_T./R./sigma./a))))) -...
    (CP_UH60_FF.*R./CT_constant_T./L_tr);
theta_knot_fn = @(beta_1s_UH60_FF) (((6.*CT_constant_T./sigma./a).*...
    (1+(3/2.*mu.^2)))- ((0.75.*theta_tw).*(1-(1.5.*mu.^2)+...
    (1.5*mu.^4))) +(1.5.*lambda_TPP_UH60_FF).*(1-(0.5.*mu.^2))) +  ...
    ((4./lock).*mu.*((vb^2)-1).*beta_1s_UH60_FF)./ ...
    (1 - (mu.^2) +(9/4*mu.^4)) ;
theta_1s = @(beta_1c_UH60_FF, beta_1s_UH60_FF,theta_knot_UH60_FF)-...
    beta_1c_UH60_FF + ((1./(1+(1.5*mu.^2))).*((-8/3*mu.*...
    (theta_knot_UH60_FF+ (0.75.*theta_tw) - (0.75*lambda_TPP_UH60_FF)))+...
    ( (8/lock).*((vb^2)-1).*(beta_1s_UH60_FF) ) ));
beta_knot = @(beta_1c_UH60_FF, theta_1s_UH60_FF, theta_knot_UH60_FF)...
    (lock/vb.^2)*(((1+(mu.^2)).*theta_knot_UH60_FF/8)+...
    ((1+mu.^2).*theta_tw./10)+((1/6).*mu.*...
    (beta_1c_UH60_FF+theta_1s_UH60_FF))-(lambda_TPP_UH60_FF/6));
theta_1c = @(beta_1s_UH60_FF, beta_knot_UH60_FF, beta_1c_UH60_FF)...
    beta_1s_UH60_FF + ((1./(1+(0.5*mu.^2))).*...
    ((4/3.*mu.*beta_knot_UH60_FF) + ((8./lock).*...
    ((vb.^2)-1).*beta_1c_UH60_FF)));
CH_TPP = @(theta_knot_UH60_FF, theta_1s_UH60_FF,...
    theta_1c_UH60_FF, beta_knot_UH60_FF) ((sigma.*a./2).* ...
    ((((1/2).*mu.*lambda_TPP_UH60_FF.*...
    (theta_knot_UH60_FF+(0.5.*theta_tw)))) - ...
    (((1/6).*beta_knot_UH60_FF.*theta_1c_UH60_FF) + ...
    ((1/4).*theta_1s_UH60_FF.*lambda_TPP_UH60_FF) +...
    ((1/4).*mu.*beta_knot_UH60_FF.^2)))) + (sigma.*cd0.*mu./4);
CY_TPP = @(theta_knot_UH60_FF, beta_knot_UH60_FF,...
    theta_1s_UH60_FF, theta_1c_UH60_FF) -(sigma.*a./2).*...
    ( ((3/4).*mu.*beta_knot_UH60_FF.*(theta_knot_UH60_FF+((2/3).*...
    theta_tw))) +((1/4).*theta_1c_UH60_FF.*lambda_TPP_UH60_FF) +...
    ((1/6).*beta_knot_UH60_FF.*theta_1s_UH60_FF.*(1+(3.*mu.^2) )) - ...
    ((3/2).*mu.*beta_knot_UH60_FF.*lambda_TPP_UH60_FF));

theta_fn = @(theta_knot_UH60_FF, theta_1s_UH60_FF, theta_1c_UH60_FF, psi)...
    theta_knot_UH60_FF + theta_1c_UH60_FF.*cos(psi) + (theta_1s_UH60_FF.*sin(psi));
theta_dot_fn = @(theta_1s_UH60_FF, theta_1c_UH60_FF, psi) -...
    theta_1c_UH60_FF.*sin(psi) + theta_1s_UH60_FF.*cos(psi);
theta_star_fn = @(theta_dot) theta_dot./omega;

beta_fn = @(beta_knot_UH60_FF, beta_1s_UH60_FF, beta_1c_UH60_FF, psi) beta_knot_UH60_FF + (beta_1c_UH60_FF.*cos(psi)) + (beta_1s_UH60_FF.*sin(psi));
beta_dot_fn = @(beta_1s_UH60_FF, beta_1c_UH60_FF, psi) - beta_1c_UH60_FF.*sin(psi) + beta_1s_UH60_FF.*cos(psi);
beta_star_fn = @(beta_dot) beta_dot./omega;



% Based on mu., lambda, generate the data for plots
while epsilon > 0.004
    CY_TPP_old = CY_TPP_UH60_FF;
    beta_1c_UH60_FF = beta_1c(CH_TPP_UH60_FF);
    beta_1s_UH60_FF = beta_1s(CY_TPP_UH60_FF);

    alpha_shaft_UH60_FF = alpha_shaft(CH_TPP_UH60_FF);
    phi_shaft_UH60_FF = phi_shaft(CY_TPP_UH60_FF);

    theta_knot_UH60_FF = theta_knot_fn(beta_1s_UH60_FF);
    theta_1s_UH60_FF = theta_1s(beta_1c_UH60_FF, beta_1s_UH60_FF,theta_knot_UH60_FF);

    beta_knot_UH60_FF =  beta_knot(beta_1c_UH60_FF, theta_1s_UH60_FF, theta_knot_UH60_FF);
    theta_1c_UH60_FF = theta_1c(beta_1s_UH60_FF, beta_knot_UH60_FF, beta_1c_UH60_FF);

    CH_TPP_UH60_FF = CH_TPP(theta_knot_UH60_FF, theta_1s_UH60_FF,theta_1c_UH60_FF, beta_knot_UH60_FF);
    CY_TPP_UH60_FF = CY_TPP(theta_knot_UH60_FF, beta_knot_UH60_FF, theta_1s_UH60_FF, theta_1c_UH60_FF);

    epsilon = CY_TPP_UH60_FF - CY_TPP_old;
end
[beta_knot_grid, psi_grid] = meshgrid(beta_knot_UH60_FF, psi);
[beta_1s_grid, psi_grid] = meshgrid(beta_1s_UH60_FF, psi);
[beta_1c_grid, psi_grid] = meshgrid(beta_1c_UH60_FF, psi);

[theta_knot_grid, psi_grid] = meshgrid(theta_knot_UH60_FF, psi);
[theta_1s_grid, psi_grid] = meshgrid(theta_1s_UH60_FF, psi);
[theta_1c_grid, psi_grid] = meshgrid(theta_1c_UH60_FF, psi);

theta = theta_fn(theta_knot_grid, theta_1s_grid, theta_1c_grid, psi_grid);
theta_dot = theta_dot_fn(theta_1s_grid, theta_1c_grid, psi_grid);
theta_star = theta_star_fn(theta_dot);

beta = beta_fn(beta_knot_grid, beta_1s_grid, beta_1c_grid, psi_grid);
beta_dot = beta_dot_fn(beta_1s_grid, beta_1c_grid, psi_grid);
beta_star = beta_star_fn(beta_dot);
% beta = zeros(length(mu), length(psi));
% beta_dot = zeros(length(mu), length(psi));
% beta_star = zeros(length(mu), length(psi));
% for i = 1: length(mu)
%     for j = 1: length(psi)
%         beta(i,j) = beta_fn(beta_knot_UH60_FF(i), beta_1s_UH60_FF(i), beta_1c_UH60_FF(i), psi(j));
%         beta_dot(i,j) = beta_dot_fn(beta_1s_UH60_FF(i), beta_1c_UH60_FF(i), psi(j));
%         beta_star(i,j) = beta_star_fn(beta_dot(i, j));
%     end
% end

trim_inflow = [beta_1c_UH60_FF; beta_1s_UH60_FF; alpha_shaft_UH60_FF; phi_shaft_UH60_FF; theta_knot_UH60_FF; theta_1s_UH60_FF; beta_knot_UH60_FF; theta_1c_UH60_FF];

end